ANGRY_FACE_PATH = 'icons/angry_face.png'
CARD_ICON_PATH = 'icons/card.png'
HAPPY_FACE_PATH = 'icons/happy_face.png'
TICK_MARK_PATH = 'icons/tick_mark.png'
X_MARK_PATH = 'icons/x_mark.png'
BACKGROUND_SIZE = (96, 64)
MAX_TEXT_WIDTH = 90
TEXT_LINES_SPACING = 6
RADIO_BUTTON_START_Y = 20
RADIO_BUTTON_SPACING = 12
CIRCLE_X = 5
RADIO_BUTTON_TEXT_X = 12
TITLE_START_COORDS = (3, 2)
MARKS_SIZE = (24, 24)
FACES_SIZE = (16, 16)
CARDS_ICON_SIZE = (31, 24)
DYNAMIC_TEXT_COORDS = (3, 20)
DYNAMIC_INTERFACE_ICON_COORDS = (40, 45)
STATIC_INTERFACE_ICON_COORDS = (35, 35)
MAIN_MENU_TITLE = "Wybierz opcje"
MAIN_MENU_OPTIONS = ["Kup bilet", "Sprawdz bilet", "Doladowanie"]
CHARGE_CARD_TITLE = "Kwota doladowania:"
CHARGE_CARD_OPTIONS = ["5zl", "10zl", "50zl"]
TICKET_CHOICE_TITLE ="Wybierz bilet"
TICKET_CHOICE_OPTIONS = ["Jednorazowy", "Czasowy"]
VALIDITY_TIME_TITLE = "Czas waznosci:"
VALIDITY_TIME_OPTIONS = ["15min", "30min", "1h"]
TAP_CARD_TITLE = 'Przyloz karte miejska'
CHARGE_CARD_SUCCESS_TITLE = 'Pomyslnie doladowano'
BOUGHT_SUCCESSFULLY_TITLE = 'Zakup wykonany pomyslnie'
NOT_BOUGHT_TITLE = 'Platnosc odrzucona'
YOUR_TICKET_TITLE = 'Twoj bilet'
CARD_REJECTED_TITLE = 'Karta odrzucona'
